rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - jruby-19mode
  - rbx-19mode

script: "bundle exec rake"

gemfile:
  - gemfiles/3.0.gemfile
  - gemfiles/3.1.gemfile
  - gemfiles/3.2.gemfile

matrix:
  allow_failures:
    - rvm: jruby-19mode
    - rvm: rbx-19mode
    - rvm: 2.0.0